Build and run

diff --git a/.github/workflows/build-vs-testflinger.yml b/.github/workflows/build-vs-testflinger.yml
--- a/.github/workflows/build-vs-testflinger.yml
+++ b/.github/workflows/build-vs-testflinger.yml
@@ -48,13 +48,19 @@ jobs:
 
       - name: Check test status
         run: |
+          set -e
+          testflinger results ${{ steps.submit-job.outputs.id }} > results.json
           status=$(jq '.test_status' results.json)
-          if [ "$status" -ne 0 ]; then
-            echo "testflinger task failed with status $status"
-            jq -r '.test_output' results.json
+          if ! [[ "$status" =~ ^[0-9]+$ ]]; then
+            echo "Invalid or missing test_status in results.json"
             exit 1
+          fi
+          if [ "$status" -ne 0 ]; then
+              echo "testflinger task failed with status $status"
+              jq -r '.test_output' results.json
+              exit 1
           else
-            echo "testflinger task succeeded"
+              echo "testflinger task succeeded"
           fi
 
 
@@ -95,11 +101,17 @@ jobs:
 
       - name: Check test status
         run: |
+          set -e
+          testflinger results ${{ steps.submit-job.outputs.id }} > results.json
           status=$(jq '.test_status' results.json)
-          if [ "$status" -ne 0 ]; then
-            echo "testflinger task failed with status $status"
-            jq -r '.test_output' results.json
+          if ! [[ "$status" =~ ^[0-9]+$ ]]; then
+            echo "Invalid or missing test_status in results.json"
             exit 1
+          fi
+          if [ "$status" -ne 0 ]; then
+              echo "testflinger task failed with status $status"
+              jq -r '.test_output' results.json
+              exit 1
           else
-            echo "testflinger task succeeded"
+              echo "testflinger task succeeded"
           fi
